In [79]:
import numpy as np 
c=np.array([-2,-3])   #min z=-2x1-3x2
b=np.array([[8],[16],[12]])   
Info=np.array([[1,2],[4,0],[0,4]]) #代表限制条件
basic=np.eye(Info.shape[0]) #产生基变量
s=np.append(Info,basic,axis=1) 
A=np.append(s,b,axis=1)
c1=np.append(c,np.zeros(Info.shape[0]))
print(c1)
print(A)


[-2. -3.  0.  0.  0.]
[[ 1.  2.  1.  0.  0.  8.]
 [ 4.  0.  0.  1.  0. 16.]
 [ 0.  4.  0.  0.  1. 12.]]


In [80]:
Cost=np.array(np.zeros(A.shape[1]))
Cost[0:c.shape[0]]=c
BV=np.array(range(c.shape[0],A.shape[1]-1))
temp=np.array([Cost[y] for y in BV]).reshape(1,3)
zjcj=Cost-np.dot(temp,A)
zjcj
print(zjcj)
zjcj_zero=[x<0 for x in zjcj[0][:zjcj[0].shape[0]-1]]
zjcj_zero



[[-2. -3.  0.  0.  0.  0.]]


[True, True, False, False, False]

In [81]:
def index(table):
    min=table[0]
    index2=0
    for i,t in enumerate(table):
        if table[i]<min:
            min=table[i]
            index2=i
    return index2
def is_bigger_zero(zjcj):
    for z in zjcj:
        if z<0:
            return False
    return True



In [82]:

from math import inf
zjcj_zero=[x for x in zjcj[0][:zjcj[0].shape[0]-1]]
while 1: 
    if is_bigger_zero(zjcj[0])==True:
        break
    ans=np.zeros(A.shape[0])
    for i in range(0,A.shape[0]):
        ans[i]=inf
    enter=index(zjcj[0][:zjcj[0].shape[0]-1])
    # zjcj_zero=[x for x in zjcj[0][:zjcj[0].shape[0]-1]]
    for i in range(0 ,A.shape[0]):
        if A[i][enter]>0:
            ans[i]=A[i][A.shape[1]-1]/A[i][enter]
        else:
            ans[i]=inf
    leave=BV[index(ans)]
    A[index(ans)]= A[index(ans)]/A[index(ans)][enter]   
    for i in range(0,A.shape[0]):
        if i!=index(ans):
            A[i]=A[i][:]-A[i][enter]*A[index(ans)]
        else:
            A[i]=A[index (ans)]
    BV[index(ans)]=enter
    res=0
    print("basis feasible vairable:") 
    for i in range(0,A.shape[0]):
        print("x",BV[i],":")
        res+=c1[BV[i]]*A[i][A.shape[1]-1]
        print(A[i][A.shape[1]-1])
    print("result:")
    print(res)
    print(A)
    print("zjcj[0]，before:")
    print(zjcj[0])
    temp=np.array([Cost[y] for y in BV]).reshape(1,3)
    # print(zjcj[0])
    zjcj[0]=zjcj[0]-np.dot(temp,A)
    print(zjcj[0])
    # print(zjcj[0])

    # print(np.dot(temp,A))
  
    # print(zjcj_zero)
    


basis feasible vairable:
x 2 :
2.0
x 3 :
16.0
x 1 :
3.0
result:
-9.0
[[ 1.    0.    1.    0.   -0.5   2.  ]
 [ 4.    0.    0.    1.    0.   16.  ]
 [ 0.    1.    0.    0.    0.25  3.  ]]
[-2.    0.    0.    0.    0.75  9.  ]
basis feasible vairable:
x 0 :
2.0
x 3 :
8.0
x 1 :
3.0
result:
-13.0
[[ 1.    0.    1.    0.   -0.5   2.  ]
 [ 0.    0.   -4.    1.    2.    8.  ]
 [ 0.    1.    0.    0.    0.25  3.  ]]
[ 0.   3.   2.   0.   0.5 22. ]
